#ifndef _VIRTUAL_CLASS_VCIOTREQPARSOR_H_BY_EUNSEOK
#define _VIRTUAL_CLASS_VCIOTREQPARSOR_H_BY_EUNSEOK

#include "stdio.h"

typedef unsigned long TransactionDataType;

typedef enum {
	REQ_GETMETHOD = 0x100000,
	REQ_PUTMETHOD = 0x200000,
	REQ_POSTMETHOD = 0x400000,
	REQ_DELMETHOD = 0x800000,
	REQMETHOD_EOF
} REQ_METHOD;

typedef enum {
	CMDLIST_NULL = 0,
	GET_PROG_STATUS = REQ_GETMETHOD | 0x000001,
	GET_TIME = REQ_GETMETHOD | 0x000002,
	GET_STOCK = REQ_GETMETHOD | 0x000004,
	GET_ACCOUNT = REQ_GETMETHOD | 0x000008,
	GUT_ORDERAUTH = REQ_GETMETHOD | 0x000010,

	PUT_ORDERAUTH = REQ_PUTMETHOD | 0x000020,

	POST_STOCKLIST = REQ_POSTMETHOD | 0x000040,
	POST_SEARCHGRAPH = REQ_POSTMETHOD | 0x000080,
	POST_ORDERSTOCK = REQ_POSTMETHOD | 0x000100,
	CMDLIST_EOF
} REQ_CMDLIST;

class vCIoTReqParsor
{
public:
	virtual ~vCIoTReqParsor(void) { printf("vCIoTReqParsor class Default-Terminate Function\n");  };

	virtual bool IoT_ReqParse(REQ_CMDLIST method, void* data, TransactionDataType transNum) = 0;
};


#endif	// _VIRTUAL_CLASS_VCIOTREQPARSOR_H_BY_EUNSEOK